[package]
name = "image-download"
version = "0.1.0"
edition = "2021"

[dependencies]
tempfile = "3.3.0"
error-chain = "0.12.4"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.31", features = ["full"] }
