[package]
name = "fullWeb-app"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
async-trait = "0.1.86"
json = "0.12.4"
serde = { version = "1.0.188" , features = ["derive"] }
surrealdb = "2.1.4"
uuid = "1.13.1"
validator = { version = "0.16.1" , features = ["derive"] }
